### ISSUE TITLE
version from raw github stopped working

### ISSUE THREAD

**Issue by coderextreme** [sergi/jsmidi#4]
The version I referenced from this link stopped working.  I will try to find out if something changed in my code, or if my code uses AJAX, and that's wiping it out.

https://raw.github.com/sergi/jsmidi/master/midi.js

May have something to do with the same origin policy.  I will download the code.

**Comment by coderextreme** [comment]
I figured it out.  I was mapping domainnames to notes, and I ran out of notes.  Easy fix to restart note mapping from index 0.

**Comment by sergi** [comment]
Glad you figured it out!
